[workspace]
members = ["tests", "contracts/ckb-std-tests", "contracts/exec-callee", "contracts/exec-caller", "contracts/exec-caller-by-code-hash"]

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'

